class_name InfiltrationTuning

const MINIMUM_TURN_LIMIT: int = 3

const MONITORED_OPERATION_TRACE_INCREASE: int = 4
const TRACKED_ACTION_TRACE_BONUS: int = 2
const POUCH_HIDE_TRACE_REDUCTION: int = 2
const CURSOR_MONITORED_TRACE_INCREASE: int = 6
const FOLDER_NAVIGATION_TRACE_INCREASE: int = 3
const DIRECT_FOLDER_JUMP_TRACE_INCREASE: int = 5

const PERMISSION_OVERRIDE_TRACE_INCREASE: int = 4
const PERMISSION_OVERRIDE_DURATION_TURNS: int = 3
const PERMISSION_OVERRIDE_MINIMUM_DURATION_TURNS: int = 1

const SHOW_HIDDEN_POUCH_EXPOSE_TRACE_INCREASE: int = 2
const PERMISSION_OVERRIDE_POUCH_EXPOSE_TRACE_INCREASE: int = 5
const SEARCH_TRACE_INCREASE: int = 7
const REWRITE_LOG_TRACE_REDUCTION: int = 8
const MOVE_TRACE_INCREASE: int = 4
const ARCHIVE_TRACE_REDUCTION: int = 2

const MULTI_WINDOW_PARALLEL_OPERATION_TRACE_COST_PER_WINDOW: int = 1

const TRACE_PER_HEAT_POINT: int = 10
const DETECTION_CLEAR_TRACE_THRESHOLD: int = 40

const STUN_DURATION_TURNS: int = 2

const DETECTION_CONTACT_DAMAGE: int = 3
const OPERATOR_MAX_HP: int = 30

const BACKUP_REPAIR_TRACE_INCREASE: int = 5

const SUCCESS_HEAT_REDUCTION: int = 1

const POUCH_SIZE_AI_MONITOR_DETECTION_THRESHOLD: int = 5
