class_name SecurityBehaviorTuning

const FIREWALL_FOLDER_NAVIGATION_TRACE_BONUS: int = 2
const AI_MONITOR_CURSOR_TRACE_BONUS: int = 1
const AI_MONITOR_SEARCH_TRACE_BONUS: int = 2
const TRACKED_ACTION_TRACE_BONUS: int = 2
const OBJECTIVE_ROUTE_TRACE_BONUS: int = 2
const OBJECTIVE_SEARCH_TRACE_BONUS: int = 3
const TRACE_MARKER_DURATION_TURNS: int = 3
const FORCED_LOCK_DURATION_TURNS: int = 2
const SCAN_PRESSURE_DURATION_TURNS: int = 2

const ANTIVIRUS_CURSOR_TRACE_BONUS: int = 2
const ANTIVIRUS_FOLDER_NAVIGATION_TRACE_BONUS: int = 3
const ANTIVIRUS_SEARCH_TRACE_BONUS: int = 3
const BACKUP_REPAIRER_CURSOR_TRACE_BONUS: int = 1
const BACKUP_REPAIRER_FOLDER_NAVIGATION_TRACE_BONUS: int = 1
const BACKUP_REPAIRER_SEARCH_TRACE_BONUS: int = 1
const BACKUP_REPAIRER_SCAN_PRESSURE_DURATION_TURNS: int = 3
