class_name ActionIds

const OPEN: String = "open"
const INSPECT: String = "inspect"
const DELETE: String = "delete"
const COPY: String = "copy"
const CUT: String = "cut"
const PASTE: String = "paste"
const CLEAN: String = "clean"
const QUARANTINE: String = "quarantine"
const COMPRESS: String = "compress"
const LOG_FORGE: String = "logforge"
const SEARCH: String = "search"
const SHOW_HIDDEN: String = "show_hidden"
const PERMISSION_OVERRIDE: String = "override"
const MOVE: String = "move"
const EXTRACT: String = "extract"
const SORT: String = "sort"
const INJECT: String = "inject"
const STUN: String = "stun"
const DECOY: String = "decoy"
